# Generated by Django 2.2.11 on 2020-08-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='proj_desc',
            field=models.CharField(max_length=400),
        ),
    ]
