# Generated by Django 2.2.11 on 2020-07-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200723_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='proj_desc',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='project',
            name='proj_image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
