# Generated by Django 2.2.11 on 2020-07-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20200726_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
    ]
